# Generated by Django 5.0.3 on 2024-03-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0002_userd_mob_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userd',
            name='mob_num',
        ),
    ]
