# Generated by Django 5.0.3 on 2024-03-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0003_remove_userd_mob_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='userd',
            name='is_voted',
            field=models.BooleanField(default=False),
        ),
    ]
