# Generated by Django 5.0.3 on 2024-03-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0004_userd_is_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='img',
            field=models.FileField(default='settings.MEDIA_ROOT/anonymous.jpg', upload_to='candidats/'),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
