# Generated by Django 5.0.3 on 2024-03-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0005_candidat_img_alter_candidat_votes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='img',
            field=models.FileField(default='settings.MEDIA_ROOT/anonymous.png', upload_to='candidats/'),
        ),
    ]
