# Generated by Django 5.0.3 on 2024-03-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0006_alter_candidat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='img',
            field=models.ImageField(default='settings.MEDIA_ROOT/anonymous.png', upload_to='candidats/'),
        ),
    ]
