# Generated by Django 5.0.3 on 2024-03-28 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0007_alter_candidat_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidat',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='candidats/'),
        ),
    ]
