# Generated by Django 5.0.3 on 2024-04-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0008_alter_candidat_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidat',
            name='otchestvo',
        ),
        migrations.AddField(
            model_name='candidat',
            name='long_desc',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='middle_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidat',
            name='short_desc',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='candidat',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
