# Generated by Django 5.0.3 on 2024-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golos', '0009_remove_candidat_otchestvo_candidat_long_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='position',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
